import type { BusinessTemplate } from '@/engine/types'

export const BUSINESSES: BusinessTemplate[] = [
  {
    id: 'cafe',
    name: 'Cafe',
    purchasePrice: 8000,
    baseIncome: 400,
    maintenance: 80,
    upgradeCost: 4000,
    upgradeIncomeBoost: 150,
    maxLevel: 3,
    description: 'A cozy neighborhood cafe with a loyal morning crowd.',
  },
  {
    id: 'restaurant',
    name: 'Restaurant',
    purchasePrice: 15000,
    baseIncome: 750,
    maintenance: 180,
    upgradeCost: 7000,
    upgradeIncomeBoost: 280,
    maxLevel: 3,
    description: 'A full-service restaurant with steady dinner traffic.',
  },
  {
    id: 'software-company',
    name: 'Software Company',
    purchasePrice: 40000,
    baseIncome: 1800,
    maintenance: 300,
    upgradeCost: 20000,
    upgradeIncomeBoost: 700,
    maxLevel: 3,
    description: 'A lean SaaS shop with recurring subscription revenue.',
  },
  {
    id: 'solar-farm',
    name: 'Solar Farm',
    purchasePrice: 60000,
    baseIncome: 2400,
    maintenance: 250,
    upgradeCost: 28000,
    upgradeIncomeBoost: 900,
    maxLevel: 3,
    description: 'Utility-scale solar array selling power back to the grid.',
  },
  {
    id: 'factory',
    name: 'Factory',
    purchasePrice: 90000,
    baseIncome: 3200,
    maintenance: 700,
    upgradeCost: 40000,
    upgradeIncomeBoost: 1200,
    maxLevel: 3,
    description: 'A manufacturing plant producing goods under contract.',
  },
  {
    id: 'retail-store',
    name: 'Retail Store',
    purchasePrice: 22000,
    baseIncome: 950,
    maintenance: 220,
    upgradeCost: 10000,
    upgradeIncomeBoost: 350,
    maxLevel: 3,
    description: 'A storefront retail shop in a busy shopping district.',
  },
  {
    id: 'warehouse',
    name: 'Warehouse',
    purchasePrice: 35000,
    baseIncome: 1300,
    maintenance: 260,
    upgradeCost: 16000,
    upgradeIncomeBoost: 480,
    maxLevel: 3,
    description: 'Logistics warehouse leased out for storage and fulfillment.',
  },
  {
    id: 'hotel',
    name: 'Hotel',
    purchasePrice: 120000,
    baseIncome: 4500,
    maintenance: 950,
    upgradeCost: 55000,
    upgradeIncomeBoost: 1700,
    maxLevel: 3,
    description: 'A full-service hotel with year-round occupancy.',
  },
]

export const BUSINESSES_BY_ID = new Map(BUSINESSES.map((b) => [b.id, b]))
