import type { InvestmentInstrument } from '@/engine/types'

// 16 original instruments across the four investment categories, mixing
// stocks and bonds. Prices/returns/volatility are the balancing knobs;
// content (names, tickers, flavor) is all original.
export const INVESTMENTS: InvestmentInstrument[] = [
  // Growth — high upside, no dividend, higher volatility
  {
    id: 'nova-robotics',
    name: 'Nova Robotics',
    ticker: 'NOVA',
    assetClass: 'stock',
    category: 'growth',
    basePrice: 64,
    risk: 0.65,
    baseReturn: 0.14,
    dividendYield: 0,
    volatility: 0.3,
    description: 'Automation and precision robotics for next-gen factories.',
  },
  {
    id: 'skyline-semiconductors',
    name: 'Skyline Semiconductors',
    ticker: 'SKYL',
    assetClass: 'stock',
    category: 'growth',
    basePrice: 88,
    risk: 0.7,
    baseReturn: 0.16,
    dividendYield: 0,
    volatility: 0.34,
    description: 'Chip designer riding the wave of edge-computing demand.',
  },
  {
    id: 'pulse-biotech',
    name: 'Pulse Biotech',
    ticker: 'PLSB',
    assetClass: 'stock',
    category: 'growth',
    basePrice: 42,
    risk: 0.75,
    baseReturn: 0.18,
    dividendYield: 0,
    volatility: 0.38,
    description: 'Clinical-stage biotech betting big on gene therapy.',
  },
  {
    id: 'vertex-aerospace',
    name: 'Vertex Aerospace',
    ticker: 'VRTX',
    assetClass: 'stock',
    category: 'growth',
    basePrice: 120,
    risk: 0.6,
    baseReturn: 0.12,
    dividendYield: 0,
    volatility: 0.26,
    description: 'Private launch vehicles and satellite constellations.',
  },
  // Dividend — steady income, lower volatility, mix of stocks and bonds
  {
    id: 'granite-utilities',
    name: 'Granite Utilities',
    ticker: 'GRAN',
    assetClass: 'stock',
    category: 'dividend',
    basePrice: 54,
    risk: 0.25,
    baseReturn: 0.05,
    dividendYield: 0.045,
    volatility: 0.1,
    description: 'Regulated power and water utility serving Meridian City.',
  },
  {
    id: 'harborline-telecom',
    name: 'Harborline Telecom',
    ticker: 'HRBL',
    assetClass: 'stock',
    category: 'dividend',
    basePrice: 47,
    risk: 0.3,
    baseReturn: 0.06,
    dividendYield: 0.05,
    volatility: 0.13,
    description: 'Fiber and mobile network operator with a loyal customer base.',
  },
  {
    id: 'meridian-municipal-bond',
    name: 'Meridian Municipal Bond',
    ticker: 'MERI',
    assetClass: 'bond',
    category: 'dividend',
    basePrice: 100,
    risk: 0.1,
    baseReturn: 0.035,
    dividendYield: 0.035,
    volatility: 0.04,
    description: 'City-issued bond funding public transit expansion.',
  },
  {
    id: 'coastal-infrastructure-bond',
    name: 'Coastal Infrastructure Bond',
    ticker: 'CSTL',
    assetClass: 'bond',
    category: 'dividend',
    basePrice: 100,
    risk: 0.12,
    baseReturn: 0.04,
    dividendYield: 0.04,
    volatility: 0.05,
    description: 'Long-dated bond backing coastal port modernization.',
  },
  // Value — undervalued, moderate return, low-moderate volatility
  {
    id: 'anchor-steel-iron',
    name: 'Anchor Steel & Iron',
    ticker: 'ANCH',
    assetClass: 'stock',
    category: 'value',
    basePrice: 36,
    risk: 0.35,
    baseReturn: 0.08,
    dividendYield: 0.02,
    volatility: 0.16,
    description: 'Heavy industry stalwart trading below book value.',
  },
  {
    id: 'ledger-financial-group',
    name: 'Ledger Financial Group',
    ticker: 'LEDG',
    assetClass: 'stock',
    category: 'value',
    basePrice: 58,
    risk: 0.32,
    baseReturn: 0.07,
    dividendYield: 0.025,
    volatility: 0.15,
    description: 'Regional bank with a conservative, well-capitalized balance sheet.',
  },
  {
    id: 'union-freight-rail',
    name: 'Union Freight Rail',
    ticker: 'UFRL',
    assetClass: 'stock',
    category: 'value',
    basePrice: 71,
    risk: 0.3,
    baseReturn: 0.075,
    dividendYield: 0.02,
    volatility: 0.14,
    description: 'Freight rail network moving goods across the continent.',
  },
  {
    id: 'kingsley-retail-holdings',
    name: 'Kingsley Retail Holdings',
    ticker: 'KRTH',
    assetClass: 'stock',
    category: 'value',
    basePrice: 29,
    risk: 0.38,
    baseReturn: 0.09,
    dividendYield: 0.015,
    volatility: 0.18,
    description: 'Discount retail chain turning around after a rough decade.',
  },
  // High Risk — speculative, very volatile
  {
    id: 'zenith-frontier-ventures',
    name: 'Zenith Frontier Ventures',
    ticker: 'ZFV',
    assetClass: 'stock',
    category: 'high_risk',
    basePrice: 18,
    risk: 0.85,
    baseReturn: 0.22,
    dividendYield: 0,
    volatility: 0.5,
    description: 'Venture holding company stacked with early-stage bets.',
  },
  {
    id: 'volt-digital-asset-fund',
    name: 'Volt Digital Asset Fund',
    ticker: 'VOLT',
    assetClass: 'stock',
    category: 'high_risk',
    basePrice: 25,
    risk: 0.9,
    baseReturn: 0.28,
    dividendYield: 0,
    volatility: 0.6,
    description: 'Fund tracking a basket of speculative digital assets.',
  },
  {
    id: 'wildcat-exploration',
    name: 'Wildcat Exploration Co.',
    ticker: 'WILD',
    assetClass: 'stock',
    category: 'high_risk',
    basePrice: 33,
    risk: 0.8,
    baseReturn: 0.2,
    dividendYield: 0,
    volatility: 0.45,
    description: 'Wildcat drilling outfit chasing untapped reserves.',
  },
  {
    id: 'apex-startup-index',
    name: 'Apex Startup Index',
    ticker: 'APEX',
    assetClass: 'stock',
    category: 'high_risk',
    basePrice: 21,
    risk: 0.88,
    baseReturn: 0.25,
    dividendYield: 0,
    volatility: 0.55,
    description: 'Index of pre-IPO startups across every sector.',
  },
]

export const INVESTMENTS_BY_ID = new Map(INVESTMENTS.map((inv) => [inv.id, inv]))
