import type { MarketRegimeDef, MarketRegimeType } from '@/engine/types'

export const MARKET_REGIMES: Record<MarketRegimeType, MarketRegimeDef> = {
  bull: {
    type: 'bull',
    name: 'Bull Market',
    description: 'Confidence is high and prices are climbing across the board.',
    categoryMultipliers: { growth: 1.15, dividend: 1.05, value: 1.08, high_risk: 1.25 },
    propertyMultiplier: 1.05,
    businessIncomeMultiplier: 1.08,
    interestRateDelta: 0,
  },
  bear: {
    type: 'bear',
    name: 'Bear Market',
    description: 'Sentiment has soured and valuations are sliding.',
    categoryMultipliers: { growth: 0.85, dividend: 0.95, value: 0.92, high_risk: 0.7 },
    propertyMultiplier: 0.95,
    businessIncomeMultiplier: 0.92,
    interestRateDelta: 0,
  },
  inflation: {
    type: 'inflation',
    name: 'Inflation',
    description: 'Rising prices are squeezing margins but boosting real assets.',
    categoryMultipliers: { growth: 0.95, dividend: 0.9, value: 1.05, high_risk: 0.9 },
    propertyMultiplier: 1.08,
    businessIncomeMultiplier: 0.95,
    interestRateDelta: 0.01,
  },
  recession: {
    type: 'recession',
    name: 'Recession',
    description: 'Economic activity is contracting across every sector.',
    categoryMultipliers: { growth: 0.8, dividend: 0.9, value: 0.85, high_risk: 0.65 },
    propertyMultiplier: 0.88,
    businessIncomeMultiplier: 0.8,
    interestRateDelta: -0.005,
  },
  interest_rate: {
    type: 'interest_rate',
    name: 'Interest Rate Hike',
    description: 'Borrowing just got more expensive across the economy.',
    categoryMultipliers: { growth: 0.9, dividend: 0.85, value: 0.95, high_risk: 0.8 },
    propertyMultiplier: 0.9,
    businessIncomeMultiplier: 0.95,
    interestRateDelta: 0.015,
  },
  tech_boom: {
    type: 'tech_boom',
    name: 'Technology Boom',
    description: 'A wave of innovation is supercharging growth stocks.',
    categoryMultipliers: { growth: 1.3, dividend: 1.0, value: 1.02, high_risk: 1.2 },
    propertyMultiplier: 1.02,
    businessIncomeMultiplier: 1.1,
    interestRateDelta: 0,
  },
  energy_crisis: {
    type: 'energy_crisis',
    name: 'Energy Crisis',
    description: 'Energy costs are spiking, rattling the broader market.',
    categoryMultipliers: { growth: 0.9, dividend: 0.95, value: 1.1, high_risk: 0.85 },
    propertyMultiplier: 0.93,
    businessIncomeMultiplier: 0.85,
    interestRateDelta: 0.005,
  },
  crash: {
    type: 'crash',
    name: 'Market Crash',
    description: 'A sudden, sharp selloff is wiping out recent gains.',
    categoryMultipliers: { growth: 0.65, dividend: 0.85, value: 0.75, high_risk: 0.45 },
    propertyMultiplier: 0.8,
    businessIncomeMultiplier: 0.75,
    interestRateDelta: -0.01,
  },
}

export const MARKET_REGIME_TYPES = Object.keys(MARKET_REGIMES) as MarketRegimeType[]
