import type { EventCard } from '@/engine/types'

export const BUSINESS_EVENTS: EventCard[] = [
  { id: 'business-001', category: 'business', title: 'Viral Marketing Hit', flavor: 'A social post about your venture goes unexpectedly viral.', effects: [{ kind: 'cash_delta', amount: 700 }] },
  { id: 'business-002', category: 'business', title: 'Key Employee Quits', flavor: 'A critical team member leaves without much notice.', effects: [{ kind: 'cash_delta', amount: -400 }] },
  { id: 'business-003', category: 'business', title: 'Supplier Discount', flavor: 'A supplier offers you a bulk discount for early payment.', effects: [{ kind: 'expense_delta', amount: -40 }] },
  { id: 'business-004', category: 'business', title: 'Equipment Breakdown', flavor: 'A critical piece of equipment fails and needs urgent repair.', effects: [{ kind: 'cash_delta', amount: -650 }] },
  { id: 'business-005', category: 'business', title: 'Big Contract Signed', flavor: 'You land a contract bigger than anything you have signed before.', effects: [{ kind: 'cash_delta', amount: 1200 }] },
  { id: 'business-006', category: 'business', title: 'Regulatory Delay', flavor: 'A permit renewal takes far longer than expected.', effects: [{ kind: 'cash_delta', amount: -350 }] },
  { id: 'business-007', category: 'business', title: 'Franchise Inquiry', flavor: 'Someone approaches you about franchising your concept.', effects: [{ kind: 'cash_delta', amount: 550 }] },
  { id: 'business-008', category: 'business', title: 'Competitor Undercuts You', flavor: 'A rival slashes prices, squeezing your margins for the season.', effects: [{ kind: 'expense_delta', amount: 55 }] },
  { id: 'business-009', category: 'business', title: 'Positive Press Coverage', flavor: 'A local paper runs a glowing feature on your business.', effects: [{ kind: 'cash_delta', amount: 450 }] },
  { id: 'business-010', category: 'business', title: 'Lease Renewal Spike', flavor: 'Your commercial lease renews at a steeper rate.', effects: [{ kind: 'expense_delta', amount: 65 }] },
  { id: 'business-011', category: 'business', title: 'Staff Training Payoff', flavor: 'A round of staff training pays off in efficiency gains.', effects: [{ kind: 'income_delta', amount: 130 }] },
  { id: 'business-012', category: 'business', title: 'Inventory Shrinkage', flavor: 'An inventory count turns up more losses than expected.', effects: [{ kind: 'cash_delta', amount: -300 }] },
  { id: 'business-013', category: 'business', title: 'Award Nomination', flavor: 'Your business is nominated for a regional excellence award.', effects: [{ kind: 'cash_delta', amount: 300 }] },
  { id: 'business-014', category: 'business', title: 'Vendor Dispute', flavor: 'A billing dispute with a vendor drags on for weeks.', effects: [{ kind: 'cash_delta', amount: -280 }] },
  { id: 'business-015', category: 'business', title: 'Automation Upgrade', flavor: 'A small automation upgrade quietly boosts your bottom line.', effects: [{ kind: 'income_delta', amount: 160 }] },
  { id: 'business-016', category: 'business', title: 'Insurance Claim Denied', flavor: 'A business insurance claim is denied on a technicality.', effects: [{ kind: 'cash_delta', amount: -500 }] },
  { id: 'business-017', category: 'business', title: 'Loyal Customer Base', flavor: 'Repeat customers keep coming back, steadying your revenue.', effects: [{ kind: 'income_delta', amount: 110 }] },
  { id: 'business-018', category: 'business', title: 'Data Breach Scare', flavor: 'A security scare costs you in remediation and customer trust.', effects: [{ kind: 'cash_delta', amount: -600 }] },
  { id: 'business-019', category: 'business', title: 'Seasonal Surge', flavor: 'A seasonal rush brings in more business than usual.', effects: [{ kind: 'cash_delta', amount: 500 }] },
  { id: 'business-020', category: 'business', title: 'Partnership Formed', flavor: 'A strategic partnership opens a new revenue stream.', effects: [{ kind: 'income_delta', amount: 200 }] },
  { id: 'business-021', category: 'business', title: 'Health Inspection Fine', flavor: 'A surprise inspection turns up a minor violation and a fine.', effects: [{ kind: 'cash_delta', amount: -220 }] },
  { id: 'business-022', category: 'business', title: 'Referral Network Grows', flavor: 'Satisfied customers start referring their friends.', effects: [{ kind: 'cash_delta', amount: 380 }] },
  { id: 'business-023', category: 'business', title: 'Software License Overrun', flavor: 'You are billed for exceeding your software license tier.', effects: [{ kind: 'cash_delta', amount: -180 }] },
  { id: 'business-024', category: 'business', title: 'Grand Reopening', flavor: 'A refreshed storefront draws a wave of curious new customers.', effects: [{ kind: 'cash_delta', amount: 480 }] },
]
