import type { EventCard } from '@/engine/types'

export const ECONOMIC_EVENTS: EventCard[] = [
  { id: 'economic-001', category: 'economic', title: 'Central Bank Signals Rate Cut', flavor: 'Policymakers hint at easier money ahead, and markets rally.', effects: [{ kind: 'market_shift', regime: 'bull' }] },
  { id: 'economic-002', category: 'economic', title: 'Inflation Report Surprises', flavor: 'Prices are rising faster than economists expected.', effects: [{ kind: 'market_shift', regime: 'inflation' }] },
  { id: 'economic-003', category: 'economic', title: 'Jobs Report Disappoints', flavor: 'Hiring slows sharply across the region.', effects: [{ kind: 'market_shift', regime: 'recession' }] },
  { id: 'economic-004', category: 'economic', title: 'Rate Hike Announced', flavor: 'The central bank raises rates to cool the economy.', effects: [{ kind: 'market_shift', regime: 'interest_rate' }] },
  { id: 'economic-005', category: 'economic', title: 'Innovation Wave', flavor: 'A wave of breakthroughs lifts the technology sector.', effects: [{ kind: 'market_shift', regime: 'tech_boom' }] },
  { id: 'economic-006', category: 'economic', title: 'Energy Supply Shock', flavor: 'A supply disruption sends energy prices spiking.', effects: [{ kind: 'market_shift', regime: 'energy_crisis' }] },
  { id: 'economic-007', category: 'economic', title: 'Consumer Confidence Slips', flavor: 'Shoppers pull back on spending amid growing uncertainty.', effects: [{ kind: 'market_shift', regime: 'bear' }] },
  { id: 'economic-008', category: 'economic', title: 'Trading Halted, Then Crashes', flavor: 'A wave of panic selling triggers a full market crash.', effects: [{ kind: 'market_shift', regime: 'crash' }] },
  { id: 'economic-009', category: 'economic', title: 'Cost of Living Adjustment', flavor: 'Your salary gets an annual cost-of-living bump.', effects: [{ kind: 'income_delta', amount: 120 }] },
  { id: 'economic-010', category: 'economic', title: 'Local Business Boom', flavor: 'The local economy is thriving and everyone benefits.', effects: [{ kind: 'cash_delta', amount: 400 }] },
  { id: 'economic-011', category: 'economic', title: 'Currency Fluctuation', flavor: 'A currency swing affects the price of imported goods.', effects: [{ kind: 'expense_delta', amount: 45 }] },
  { id: 'economic-012', category: 'economic', title: 'Housing Market Cools', flavor: 'Real estate demand softens across the region.', effects: [{ kind: 'cash_percent_of_net_worth', percent: -0.02 }] },
  { id: 'economic-013', category: 'economic', title: 'Trade Deal Signed', flavor: 'A new trade agreement opens fresh opportunities for local firms.', effects: [{ kind: 'cash_delta', amount: 500 }] },
  { id: 'economic-014', category: 'economic', title: 'Supply Chain Snarl', flavor: 'Shipping delays ripple through every industry.', effects: [{ kind: 'expense_delta', amount: 60 }] },
  { id: 'economic-015', category: 'economic', title: 'Commodity Prices Surge', flavor: 'Raw material costs spike across the board.', effects: [{ kind: 'expense_delta', amount: 70 }] },
  { id: 'economic-016', category: 'economic', title: 'Government Stimulus', flavor: 'A stimulus package puts extra cash directly in your pocket.', effects: [{ kind: 'cash_delta', amount: 900 }] },
  { id: 'economic-017', category: 'economic', title: 'Credit Tightens', flavor: 'Banks pull back on lending, making borrowing pricier.', effects: [{ kind: 'expense_delta', amount: 40 }] },
  { id: 'economic-018', category: 'economic', title: 'Productivity Surge', flavor: 'A wave of efficiency gains boosts wages across the board.', effects: [{ kind: 'income_delta', amount: 180 }] },
  { id: 'economic-019', category: 'economic', title: 'Export Demand Rises', flavor: 'Overseas demand for local goods sends business incomes higher.', effects: [{ kind: 'cash_delta', amount: 350 }] },
  { id: 'economic-020', category: 'economic', title: 'Regional Downturn', flavor: 'A slowdown in a key industry ripples through the regional economy.', effects: [{ kind: 'cash_delta', amount: -300 }] },
  { id: 'economic-021', category: 'economic', title: 'Bond Yields Jump', flavor: 'Bond investors demand higher yields amid economic uncertainty.', effects: [{ kind: 'market_shift', regime: 'interest_rate' }] },
  { id: 'economic-022', category: 'economic', title: 'Consumer Spending Rebounds', flavor: 'Retail sales bounce back stronger than anyone predicted.', effects: [{ kind: 'market_shift', regime: 'bull' }] },
  { id: 'economic-023', category: 'economic', title: 'Manufacturing Slump', flavor: 'Factory orders fall for the third month running.', effects: [{ kind: 'market_shift', regime: 'recession' }] },
  { id: 'economic-024', category: 'economic', title: 'Currency Devaluation Fears', flavor: 'Talk of devaluation spooks investors into safer assets.', effects: [{ kind: 'market_shift', regime: 'bear' }] },
]
