import type { EventCard } from '@/engine/types'

export const INVESTMENT_EVENTS: EventCard[] = [
  { id: 'investment-001', category: 'investment', title: 'Analyst Upgrade', flavor: 'A major analyst upgrades one of your holdings.', effects: [{ kind: 'cash_percent_of_net_worth', percent: 0.03 }] },
  { id: 'investment-002', category: 'investment', title: 'Earnings Miss', flavor: 'A company you are invested in misses earnings expectations.', effects: [{ kind: 'lose_random_investment_percent', percent: 0.12 }] },
  { id: 'investment-003', category: 'investment', title: 'Dividend Increase', flavor: 'One of your holdings announces a surprise dividend increase.', effects: [{ kind: 'cash_delta', amount: 300 }] },
  { id: 'investment-004', category: 'investment', title: 'Short Squeeze', flavor: 'A short squeeze sends one of your positions sharply higher.', effects: [{ kind: 'cash_percent_of_net_worth', percent: 0.06 }] },
  { id: 'investment-005', category: 'investment', title: 'Broker Fee Refund', flavor: 'Your brokerage refunds a batch of overcharged fees.', effects: [{ kind: 'cash_delta', amount: 150 }] },
  { id: 'investment-006', category: 'investment', title: 'Insider Selling Reported', flavor: 'News of insider selling rattles confidence in one of your holdings.', effects: [{ kind: 'lose_random_investment_percent', percent: 0.15 }] },
  { id: 'investment-007', category: 'investment', title: 'Stock Split Announced', flavor: 'One of your holdings announces a stock split, and sentiment improves.', effects: [{ kind: 'cash_percent_of_net_worth', percent: 0.02 }] },
  { id: 'investment-008', category: 'investment', title: 'Portfolio Rebalance Fee', flavor: 'You pay a fee to have your portfolio professionally rebalanced.', effects: [{ kind: 'cash_delta', amount: -120 }] },
  { id: 'investment-009', category: 'investment', title: 'Merger Announced', flavor: 'A company in your portfolio is acquired at a premium.', effects: [{ kind: 'cash_percent_of_net_worth', percent: 0.08 }] },
  { id: 'investment-010', category: 'investment', title: 'Guidance Cut', flavor: 'A company slashes its forward guidance, spooking shareholders.', effects: [{ kind: 'lose_random_investment_percent', percent: 0.18 }] },
  { id: 'investment-011', category: 'investment', title: 'Bond Coupon Payment', flavor: 'A bond coupon payment lands right on schedule.', effects: [{ kind: 'cash_delta', amount: 200 }] },
  { id: 'investment-012', category: 'investment', title: 'Sector Rotation', flavor: 'Investors rotate out of your sector and into another.', effects: [{ kind: 'lose_random_investment_percent', percent: 0.1 }] },
  { id: 'investment-013', category: 'investment', title: 'Buyback Announced', flavor: 'A company announces a large share buyback program.', effects: [{ kind: 'cash_percent_of_net_worth', percent: 0.04 }] },
  { id: 'investment-014', category: 'investment', title: 'Research Report Leaked', flavor: 'A leaked research report sends speculative buying into your favor.', effects: [{ kind: 'cash_percent_of_net_worth', percent: 0.05 }] },
  { id: 'investment-015', category: 'investment', title: 'Margin Call Warning', flavor: 'A margin call warning forces you to shore up your position.', effects: [{ kind: 'cash_delta', amount: -350 }] },
  { id: 'investment-016', category: 'investment', title: 'Index Inclusion', flavor: 'One of your holdings is added to a widely tracked index.', effects: [{ kind: 'cash_percent_of_net_worth', percent: 0.05 }] },
  { id: 'investment-017', category: 'investment', title: 'Fraud Investigation', flavor: 'News breaks of a fraud investigation at a company you hold.', effects: [{ kind: 'lose_random_investment_percent', percent: 0.3 }] },
  { id: 'investment-018', category: 'investment', title: 'Patent Approved', flavor: 'A key patent approval boosts confidence in your holding.', effects: [{ kind: 'cash_percent_of_net_worth', percent: 0.045 }] },
  { id: 'investment-019', category: 'investment', title: 'Currency Headwind', flavor: 'An unfavorable currency swing dents overseas earnings.', effects: [{ kind: 'lose_random_investment_percent', percent: 0.08 }] },
  { id: 'investment-020', category: 'investment', title: 'Activist Investor Steps In', flavor: 'An activist investor pushes for changes that lift the stock.', effects: [{ kind: 'cash_percent_of_net_worth', percent: 0.035 }] },
  { id: 'investment-021', category: 'investment', title: 'Credit Rating Downgrade', flavor: 'A rating agency downgrades a bond you hold.', effects: [{ kind: 'lose_random_investment_percent', percent: 0.14 }] },
  { id: 'investment-022', category: 'investment', title: 'Record Quarter', flavor: 'A company you back posts a record-breaking quarter.', effects: [{ kind: 'cash_percent_of_net_worth', percent: 0.07 }] },
  { id: 'investment-023', category: 'investment', title: 'Trading Glitch Reversed', flavor: 'A brief exchange glitch is reversed, but not before some jitters.', effects: [{ kind: 'cash_delta', amount: -100 }] },
  { id: 'investment-024', category: 'investment', title: 'Analyst Downgrade', flavor: 'An analyst downgrades one of your holdings on valuation concerns.', effects: [{ kind: 'lose_random_investment_percent', percent: 0.11 }] },
]
