import type { EventCard } from '@/engine/types'

export const NEGATIVE_EVENTS: EventCard[] = [
  { id: 'negative-001', category: 'negative', title: 'Parking Ticket', flavor: 'You forgot to feed the meter — again.', effects: [{ kind: 'cash_delta', amount: -120 }] },
  { id: 'negative-002', category: 'negative', title: 'Flat Tire', flavor: 'A pothole gets the better of your front tire.', effects: [{ kind: 'cash_delta', amount: -180 }] },
  { id: 'negative-003', category: 'negative', title: 'Lost Wallet', flavor: 'Your wallet goes missing after a night out.', effects: [{ kind: 'cash_delta', amount: -250 }] },
  { id: 'negative-004', category: 'negative', title: 'Overdraft Fee', flavor: 'A miscalculation triggers a bank overdraft fee.', effects: [{ kind: 'cash_delta', amount: -90 }] },
  { id: 'negative-005', category: 'negative', title: 'Broken Appliance', flavor: 'Your refrigerator dies on the hottest week of the year.', effects: [{ kind: 'cash_delta', amount: -600 }] },
  { id: 'negative-006', category: 'negative', title: 'Late Fee', flavor: 'A bill slips your mind and racks up a late fee.', effects: [{ kind: 'cash_delta', amount: -75 }] },
  { id: 'negative-007', category: 'negative', title: 'Rent Increase', flavor: 'Your landlord raises the rent at renewal time.', effects: [{ kind: 'expense_delta', amount: 120 }] },
  { id: 'negative-008', category: 'negative', title: 'Subscription Creep', flavor: 'You realize you have been paying for three services you forgot about.', effects: [{ kind: 'expense_delta', amount: 60 }] },
  { id: 'negative-009', category: 'negative', title: 'Pay Cut', flavor: 'Budget cuts at work mean a smaller paycheck for everyone.', effects: [{ kind: 'income_delta', amount: -150 }] },
  { id: 'negative-010', category: 'negative', title: 'Hours Reduced', flavor: 'Your shifts get trimmed back this quarter.', effects: [{ kind: 'income_delta', amount: -100 }] },
  { id: 'negative-011', category: 'negative', title: 'Fender Bender', flavor: 'A minor collision leaves you covering the deductible.', effects: [{ kind: 'cash_delta', amount: -700 }] },
  { id: 'negative-012', category: 'negative', title: 'Burst Pipe', flavor: 'A pipe bursts overnight and floods the hallway.', effects: [{ kind: 'cash_delta', amount: -900 }] },
  { id: 'negative-013', category: 'negative', title: 'Identity Theft Scare', flavor: 'Fraudulent charges appear on your card and take time to resolve.', effects: [{ kind: 'cash_delta', amount: -400 }] },
  { id: 'negative-014', category: 'negative', title: 'Legal Fees', flavor: 'A minor dispute requires you to consult a lawyer.', effects: [{ kind: 'cash_delta', amount: -850 }] },
  { id: 'negative-015', category: 'negative', title: 'Storm Damage', flavor: 'A storm knocks a tree branch through your fence.', effects: [{ kind: 'cash_delta', amount: -500 }] },
  { id: 'negative-016', category: 'negative', title: 'Phone Cracked', flavor: 'Your phone slips out of your pocket at the worst moment.', effects: [{ kind: 'cash_delta', amount: -220 }] },
  { id: 'negative-017', category: 'negative', title: 'Unexpected Audit Prep', flavor: 'You pay an accountant to help you get your paperwork in order.', effects: [{ kind: 'cash_delta', amount: -300 }] },
  { id: 'negative-018', category: 'negative', title: 'Bad Investment Tip', flavor: 'You act on a tip that turns out to be worthless, taking a hit.', effects: [{ kind: 'lose_random_investment_percent', percent: 0.2 }] },
  { id: 'negative-019', category: 'negative', title: 'Forced Liquidation', flavor: 'A cash crunch forces you to sell an asset at a bad time.', effects: [{ kind: 'force_sell_random_asset' }] },
  { id: 'negative-020', category: 'negative', title: 'Emergency Repair Loan', flavor: 'You have no choice but to borrow to cover a sudden repair.', effects: [{ kind: 'liability_delta', amount: 2000 }] },
  { id: 'negative-021', category: 'negative', title: 'Utility Spike', flavor: 'A heatwave sends your utility bill soaring for the season.', effects: [{ kind: 'cash_delta', amount: -260 }] },
  { id: 'negative-022', category: 'negative', title: 'Missed Bus', flavor: 'You miss the last bus home and have to pay for a ride.', effects: [{ kind: 'cash_delta', amount: -60 }] },
  { id: 'negative-023', category: 'negative', title: 'Grocery Spike', flavor: 'A supply shortage sends grocery prices up for weeks.', effects: [{ kind: 'expense_delta', amount: 80 }] },
  { id: 'negative-024', category: 'negative', title: 'Pet Emergency', flavor: 'Your pet needs an unplanned trip to the vet.', effects: [{ kind: 'cash_delta', amount: -450 }] },
  { id: 'negative-025', category: 'negative', title: 'Scam Attempt', flavor: 'You nearly fall for a scam and lose a small amount before catching on.', effects: [{ kind: 'cash_delta', amount: -300 }] },
  { id: 'negative-026', category: 'negative', title: 'Vandalism', flavor: 'Someone keys your car in a parking lot.', effects: [{ kind: 'cash_delta', amount: -350 }] },
  { id: 'negative-027', category: 'negative', title: 'Double Booked', flavor: 'A scheduling mixup costs you a cancellation fee.', effects: [{ kind: 'cash_delta', amount: -150 }] },
  { id: 'negative-028', category: 'negative', title: 'Wage Garnishment Notice', flavor: 'An old bill catches up with you via a temporary garnishment.', effects: [{ kind: 'cash_percent_of_cash', percent: -0.1 }] },
]
