import type { EventCard } from '@/engine/types'

export const NEUTRAL_EVENTS: EventCard[] = [
  { id: 'neutral-001', category: 'neutral', title: 'Quiet Week', flavor: 'Nothing much happens — you spend a quiet week at home.', effects: [] },
  { id: 'neutral-002', category: 'neutral', title: 'Routine Checkup', flavor: 'A routine appointment comes and goes without incident.', effects: [] },
  { id: 'neutral-003', category: 'neutral', title: 'Neighborhood Gossip', flavor: 'You catch up on neighborhood news — interesting, but no impact on your wallet.', effects: [] },
  { id: 'neutral-004', category: 'neutral', title: 'Weather Report', flavor: 'A mild week of ordinary weather passes by.', effects: [] },
  { id: 'neutral-005', category: 'neutral', title: 'Errand Day', flavor: 'You knock out a long list of errands with nothing unusual to report.', effects: [] },
  { id: 'neutral-006', category: 'neutral', title: 'Coin Flip', flavor: 'A friend bets you on a coin flip for fun — it evens out either way.', effects: [{ kind: 'cash_delta', amount: 150 }] },
  { id: 'neutral-007', category: 'neutral', title: 'Swap Meet', flavor: 'You trade a few odds and ends at a swap meet, roughly breaking even.', effects: [{ kind: 'cash_delta', amount: -50 }] },
  { id: 'neutral-008', category: 'neutral', title: 'Recalculated Budget', flavor: 'You redo your monthly budget and shift a few line items around.', effects: [{ kind: 'expense_delta', amount: 20 }] },
  { id: 'neutral-009', category: 'neutral', title: 'Minor Reimbursement', flavor: 'A small reimbursement clears from an old expense report.', effects: [{ kind: 'cash_delta', amount: 100 }] },
  { id: 'neutral-010', category: 'neutral', title: 'Slow News Day', flavor: 'The markets are flat and so is your week.', effects: [] },
  { id: 'neutral-011', category: 'neutral', title: 'Borrowed Umbrella', flavor: 'You lend a coworker an umbrella; they return it with a small thank-you gift.', effects: [{ kind: 'cash_delta', amount: 40 }] },
  { id: 'neutral-012', category: 'neutral', title: 'Recycled Furniture', flavor: 'You sell an old desk for close to what you paid.', effects: [{ kind: 'cash_delta', amount: 60 }] },
  { id: 'neutral-013', category: 'neutral', title: 'Paperwork Day', flavor: 'You spend the day filing paperwork — tedious, but uneventful.', effects: [] },
  { id: 'neutral-014', category: 'neutral', title: 'Rescheduled Meeting', flavor: 'An important meeting gets pushed back a week.', effects: [] },
  { id: 'neutral-015', category: 'neutral', title: 'Split the Bill', flavor: 'Dinner with friends costs a little more than planned, but it was worth it.', effects: [{ kind: 'cash_delta', amount: -80 }] },
  { id: 'neutral-016', category: 'neutral', title: 'Odd Job', flavor: 'You help a neighbor move furniture for some quick cash.', effects: [{ kind: 'cash_delta', amount: 120 }] },
  { id: 'neutral-017', category: 'neutral', title: 'Market Chatter', flavor: 'You overhear conflicting opinions about where the market is headed.', effects: [] },
  { id: 'neutral-018', category: 'neutral', title: 'Software Update', flavor: 'A routine update to your budgeting app changes nothing important.', effects: [] },
  { id: 'neutral-019', category: 'neutral', title: 'Commute Reroute', flavor: 'Road work reroutes your commute for a week — mildly annoying, no cost.', effects: [] },
  { id: 'neutral-020', category: 'neutral', title: 'Book Club Pick', flavor: 'You buy this month’s book club pick and enjoy a relaxing read.', effects: [{ kind: 'cash_delta', amount: -25 }] },
  { id: 'neutral-021', category: 'neutral', title: 'Loyalty Points', flavor: 'You redeem a small stash of loyalty points for a modest credit.', effects: [{ kind: 'cash_delta', amount: 70 }] },
  { id: 'neutral-022', category: 'neutral', title: 'Housekeeping', flavor: 'You spend the weekend tidying up — good for the soul, neutral for the wallet.', effects: [] },
]
