import type { EventCard } from '@/engine/types'

export const POSITIVE_EVENTS: EventCard[] = [
  { id: 'positive-001', category: 'positive', title: 'Signing Bonus', flavor: 'Your employer surprises you with a one-time signing bonus.', effects: [{ kind: 'cash_delta', amount: 800 }] },
  { id: 'positive-002', category: 'positive', title: 'Found Money', flavor: 'You find an old envelope of cash tucked in a coat pocket.', effects: [{ kind: 'cash_delta', amount: 300 }] },
  { id: 'positive-003', category: 'positive', title: 'Referral Reward', flavor: 'A friend you referred gets hired, and you collect the referral bonus.', effects: [{ kind: 'cash_delta', amount: 500 }] },
  { id: 'positive-004', category: 'positive', title: 'Garage Sale Windfall', flavor: 'Your weekend garage sale does surprisingly well.', effects: [{ kind: 'cash_delta', amount: 350 }] },
  { id: 'positive-005', category: 'positive', title: 'Contest Winner', flavor: 'You win a local raffle you barely remember entering.', effects: [{ kind: 'cash_delta', amount: 1000 }] },
  { id: 'positive-006', category: 'positive', title: 'Side Gig Takes Off', flavor: 'Your weekend side project starts bringing in steady cash.', effects: [{ kind: 'income_delta', amount: 150 }] },
  { id: 'positive-007', category: 'positive', title: 'Skill Certification', flavor: 'You pass a professional certification exam, opening doors at work.', effects: [{ kind: 'income_delta', amount: 200 }] },
  { id: 'positive-008', category: 'positive', title: 'Promotion Announced', flavor: 'Your manager pulls you aside with good news — you have been promoted.', effects: [{ kind: 'income_delta', amount: 300 }] },
  { id: 'positive-009', category: 'positive', title: 'Frugal Month', flavor: 'You find clever ways to trim your monthly bills for good.', effects: [{ kind: 'expense_delta', amount: -100 }] },
  { id: 'positive-010', category: 'positive', title: 'Loyalty Discount', flavor: 'Your insurer rewards your clean record with a permanent discount.', effects: [{ kind: 'expense_delta', amount: -60 }] },
  { id: 'positive-011', category: 'positive', title: 'Inheritance', flavor: 'A distant relative leaves you a modest inheritance.', effects: [{ kind: 'cash_percent_of_net_worth', percent: 0.08 }] },
  { id: 'positive-012', category: 'positive', title: 'Community Grant', flavor: 'You are awarded a small-business community grant.', effects: [{ kind: 'cash_delta', amount: 1500 }] },
  { id: 'positive-013', category: 'positive', title: 'Tax Refund Surprise', flavor: 'An amended return nets you an unexpected refund.', effects: [{ kind: 'cash_delta', amount: 650 }] },
  { id: 'positive-014', category: 'positive', title: 'Networking Payoff', flavor: 'A contact from a conference sends real business your way.', effects: [{ kind: 'cash_delta', amount: 700 }] },
  { id: 'positive-015', category: 'positive', title: 'Lucky Timing', flavor: 'You happen to be in the right place at the right time for a quick flip.', effects: [{ kind: 'cash_delta', amount: 450 }] },
  { id: 'positive-016', category: 'positive', title: 'Debt Forgiven', flavor: 'A lingering old debt is quietly written off.', effects: [{ kind: 'liability_delta', amount: -1000 }] },
  { id: 'positive-017', category: 'positive', title: 'Freelance Windfall', flavor: 'A freelance client pays a bonus for finishing early.', effects: [{ kind: 'cash_delta', amount: 550 }] },
  { id: 'positive-018', category: 'positive', title: 'Cashback Rewards', flavor: 'Your rewards card statement arrives with a fat cashback credit.', effects: [{ kind: 'cash_delta', amount: 250 }] },
  { id: 'positive-019', category: 'positive', title: 'Mentor Advice', flavor: 'A mentor points you toward a smarter way to manage your budget.', effects: [{ kind: 'expense_delta', amount: -75 }] },
  { id: 'positive-020', category: 'positive', title: 'Landlord Credit', flavor: 'Your landlord issues a rent credit after a maintenance delay.', effects: [{ kind: 'cash_delta', amount: 300 }] },
  { id: 'positive-021', category: 'positive', title: 'Overtime Approved', flavor: 'Extra hours at work translate directly into extra pay.', effects: [{ kind: 'cash_delta', amount: 400 }] },
  { id: 'positive-022', category: 'positive', title: 'Community Recognition', flavor: 'You are recognized publicly for volunteer work, and it opens a paid opportunity.', effects: [{ kind: 'cash_delta', amount: 500 }, { kind: 'income_delta', amount: 100 }] },
  { id: 'positive-023', category: 'positive', title: 'Warranty Payout', flavor: 'An old appliance warranty claim finally comes through.', effects: [{ kind: 'cash_delta', amount: 320 }] },
  { id: 'positive-024', category: 'positive', title: 'Second Job Offer', flavor: 'You pick up a reliable part-time gig on weekends.', effects: [{ kind: 'income_delta', amount: 180 }] },
  { id: 'positive-025', category: 'positive', title: 'Estate Sale Find', flavor: 'You spot an underpriced item at an estate sale and resell it for a profit.', effects: [{ kind: 'cash_delta', amount: 380 }] },
  { id: 'positive-026', category: 'positive', title: 'Utility Rebate', flavor: 'An energy-efficiency rebate check shows up in the mail.', effects: [{ kind: 'cash_delta', amount: 220 }] },
  { id: 'positive-027', category: 'positive', title: 'Clean Bill Bonus', flavor: 'Your landlord returns your full security deposit plus interest.', effects: [{ kind: 'cash_delta', amount: 260 }] },
  { id: 'positive-028', category: 'positive', title: 'Negotiation Win', flavor: 'You negotiate a better rate on a recurring service.', effects: [{ kind: 'expense_delta', amount: -50 }] },
]
