insert into public.personal_event_catalog (id, name, description, effect_kind, amount, pct) values
('pe_1','Signing Bonus','Your employer pays out a one-time signing bonus.','cash',1500,null),
('pe_2','Medical Expense','An unexpected medical bill arrives.','cash',-2000,null),
('pe_3','Inheritance Windfall','A distant relative leaves you an inheritance.','cash_pct_net_worth',null,0.05),
('pe_4','Vehicle Repair Bill','Your vehicle needs urgent repairs.','cash',-800,null),
('pe_5','Investment Opportunity','A once-in-a-lifetime deal lands in your lap — you acquire an asset for free.','grant_card',null,null),
('pe_6','Promotion at Work','You are promoted, permanently raising your salary.','salary',300,null),
('pe_7','Tax Refund','A tax refund arrives in your account.','cash',600,null),
('pe_8','Legal Settlement','You win a legal settlement.','cash',2500,null),
('pe_9','Home Repair Cost','A home repair costs more than expected.','cash',-1200,null),
('pe_10','Wedding Gift','You receive a generous cash gift.','cash',1000,null),
('pe_11','Identity Theft','You lose money resolving a case of identity theft.','cash',-1500,null),
('pe_12','Side Hustle Income','A side project pays off nicely this round.','cash',700,null),
('pe_13','Stock Tip Payoff','A well-timed tip nets you an unexpected gain.','cash_pct_net_worth',null,0.03),
('pe_14','Emergency Fund Depletion','An emergency drains part of your savings.','cash_pct_net_worth',null,-0.04),
('pe_15','Lawsuit Payout','You are ordered to pay damages in a lawsuit.','cash',-3000,null),
('pe_16','Lottery Ticket Win','A lucky ticket pays off.','cash',2000,null),
('pe_17','Freelance Contract','A short freelance contract brings in extra cash.','cash',900,null),
('pe_18','Pet Emergency Vet Bill','Your pet needs emergency veterinary care.','cash',-600,null),
('pe_19','Family Support Request','A family member asks for financial help.','cash',-1000,null),
('pe_20','Bonus Dividend Payout','One of your holdings issues a surprise bonus payout.','cash',1100,null),
('pe_21','Car Accident (Uninsured)','An accident leaves you covering repair costs out of pocket.','cash',-1800,null),
('pe_22','Scholarship Award','You receive a scholarship award.','cash',1300,null),
('pe_23','Job Loss Setback','A layoff temporarily reduces your income.','salary',-200,null),
('pe_24','Charity Windfall Received','A local charity distributes an unexpected windfall.','cash',500,null);
